export const UPDATE_FORM = 'Upload/UPDATE_FORM';
export const UPLOAD_FORM = 'Upload/UPLOAD_FORM';
export const UPLOAD_FORM_SUCCESSFUL = 'Upload/UPLOAD_FORM_SUCCESSFUL';
export const SEARCH_TEXT_REQUEST = 'Upload/SEARCH_TEXT_REQUEST';
export const SEARCH_TEXT_SUCCESSFUL = 'Upload/SEARCH_TEXT_SUCCESSFUL';
